name: country
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  get_it: ^7.7.0
  graphql_flutter: ^5.1.2
  injectable: ^2.4.2
  multiple_result: ^5.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  graphql_codegen: ^0.12.2
  build_runner: ^2.4.11
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true
